# Module 4 Data analysis with python

## Alumno: Luis Jose Navarrete Baduy
## Matricula: A01793919
## Profesora: María de la Paz Rico Fernández

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

### Simple Linear Regression and Multiple LR

La regresion lineal simple nos permite realizar la prediccion entre la variable independiente (X) y la variable dependiente (Y) la variable X trata de encontrar el coeficiente y la pendiente para minimizar el error entre la prediccion y el valor actual Y.



In [2]:
path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/automobileEDA.csv'
df = pd.read_csv(path)

Se declara el modelo a utilizar y las variable independiente y dependiente con lo que se va a entrenar el modelo

In [4]:
lm = LinearRegression()
X = df[['highway-mpg']]
Y = df[['price']]
lm.fit(X, Y)

LinearRegression()

Permite realizar la prediccion usando el modelo entrenado

In [5]:
yhat = lm.predict(X)

Imprime la pendiente o el parametro b0 y los coeficientes en este caso es b1

In [6]:
lm.intercept_, lm.coef_

(array([38423.30585816]), array([[-821.73337832]]))

### Multiple Linear Regression

In [8]:
lm = LinearRegression()
Z = df[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']]
Y = df[['price']]
lm.fit(Z, Y)

LinearRegression()

In [9]:
yhat = lm.predict(Z)

In [10]:
lm.intercept_, lm.coef_

(array([-15806.62462633]),
 array([[53.49574423,  4.70770099, 81.53026382, 36.05748882]]))